### ISSUE TITLE
Invalid paper link

### ISSUE THREAD

**Issue by xiujiesong** [cuixuage/KDDCup2022-ESCI#1]
Hi,

Thanks for sharing your work. Your paper link is no more valid, where can I find it?

**Comment by cuixuage** [comment]
Thanks for your information~~  
The paper cannot be downloaded due to the change of the paper storage site.   
And I have updated the paper link now.   
```
https://amazonkddcup.github.io/papers/4952.pdf   
```
   
Additional information:  
Here you can find more papers，https://amazonkddcup.github.io/

If you would like to discuss the paper details further, please feel free to contact me~

Best

**Comment by xiujiesong** [comment]
Thanks for ur quick reply and information ;)
